# Generated by Django 5.2.17 on 2026-09-03 00:36

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_email_student_form_standard_student_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default=students.models._generate_student_id, editable=False, max_length=50, null=True, unique=True),
        ),
    ]
