# Generated by Django 5.2.17 on 2026-09-03 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='form_standard',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
    ]
