# Generated by Django 5.2.17 on 2026-09-04 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_talentcategory_alter_talent_options_and_more'),
        ('students', '0006_remove_student_email_remove_student_form_standard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=20)),
                ('level_type', models.CharField(choices=[('standard', 'Standard'), ('form', 'Form')], max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_levels', to='core.country')),
            ],
            options={
                'ordering': ['level_type', 'order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='students', to='students.educationlevel'),
        ),
        migrations.AddConstraint(
            model_name='educationlevel',
            constraint=models.UniqueConstraint(fields=('country', 'code'), name='unique_education_level_per_country'),
        ),
    ]
