# Generated by Django 6.0.5 on 2026-05-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('region_manager', 'Region Manager'), ('zone_manager', 'Zone Manager'), ('district_manager', 'District Manager'), ('ward_manager', 'Ward Manager'), ('head_teacher', 'Head Teacher'), ('sport_teacher', 'Sport Teacher')], max_length=30),
        ),
    ]
