# Generated by Django 6.0.6 on 2026-06-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('talent_admin', 'Talent Admin'), ('region_manager', 'Region Manager'), ('zone_manager', 'Zone Manager'), ('district_manager', 'District Manager'), ('ward_manager', 'Ward Manager'), ('head_teacher', 'Head Teacher'), ('sport_teacher', 'Sport Teacher')], max_length=30),
        ),
    ]
