# Generated by Django 6.0.6 on 2026-08-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_announcement_id_alter_country_id_and_more'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[
                ('talent_admin', 'Talent Admin'),
                ('region_manager', 'Region Manager'),
                ('zone_manager', 'Zone Manager'),
                ('district_manager', 'District Manager'),
                ('ward_manager', 'Ward Manager'),
                ('head_teacher', 'Head Teacher'),
                ('sport_teacher', 'Sport Teacher'),
                ('student', 'Student'),
            ], max_length=30),
        ),
        migrations.AddField(
            model_name='user',
            name='student',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='students.student'),
        ),
    ]