# Generated by Django 5.2.17 on 2026-08-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parent_user_school_student_count_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('talent_admin', 'Talent Admin'), ('region_manager', 'Region Manager'), ('zone_manager', 'Zone Manager'), ('district_manager', 'District Manager'), ('ward_manager', 'Ward Manager'), ('head_teacher', 'Head Teacher'), ('sport_teacher', 'Sport Teacher'), ('student', 'Student'), ('parent', 'Parent')], max_length=30),
        ),
    ]
