# Generated by Django 5.2.17 on 2026-08-30 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_talentevaluation_grade_alter_announcement_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership_type',
            field=models.CharField(choices=[('public', 'Public'), ('government', 'Government'), ('private', 'Private')], default='public', max_length=20),
        ),
    ]
