# Generated by Django 5.2.17 on 2026-08-30 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_school_is_approved_alter_school_ownership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolOwnershipType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='school',
            name='ownership_type',
            field=models.CharField(default='Government', max_length=100),
        ),
    ]
