# Generated by Django 5.2.17 on 2026-09-02 01:14

import django.db.models.deletion
from django.db.models import Case, IntegerField, When
from django.db import migrations, models


def copy_clubs_to_country_catalog(apps, schema_editor):
    Club = apps.get_model('core', 'Club')
    CountryClub = apps.get_model('core', 'CountryClub')
    SchoolClub = apps.get_model('core', 'SchoolClub')
    ClubTeacher = apps.get_model('core', 'ClubTeacher')
    StudentClubMembership = apps.get_model('core', 'StudentClubMembership')
    TalentSubmission = apps.get_model('core', 'TalentSubmission')
    club_id_map = {}

    for club in Club.objects.select_related('school').all():
        country_club, _ = CountryClub.objects.get_or_create(
            country_id=club.school.country_id,
            name=club.name,
            defaults={
                'focus': club.focus,
                'description': club.description,
                'is_active': club.is_active,
            },
        )
        school_club, _ = SchoolClub.objects.get_or_create(
            school_id=club.school_id,
            country_club_id=country_club.id,
            defaults={
                'is_active': club.is_active,
            },
        )
        club_id_map[club.id] = school_club.id

    remap = Case(
        *[When(club_id=old_id, then=new_id) for old_id, new_id in club_id_map.items()],
        output_field=IntegerField(),
    )
    for related_model in (ClubTeacher, StudentClubMembership, TalentSubmission):
        related_model.objects.filter(club_id__in=club_id_map).update(club_id=remap)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_schoolownershiptype_alter_school_ownership_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('focus', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='core.country')),
            ],
            options={
                'ordering': ['country', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('country_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_selections', to='core.countryclub')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='core.school')),
            ],
            options={
                'ordering': ['school', 'country_club__name'],
            },
        ),
        migrations.RunPython(copy_clubs_to_country_catalog, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name='club',
            name='unique_club_name_per_school',
        ),
        migrations.RemoveField(
            model_name='club',
            name='school',
        ),
        migrations.RemoveField(
            model_name='club',
            name='talents',
        ),
        migrations.RemoveField(
            model_name='club',
            name='teachers',
        ),
        migrations.AlterField(
            model_name='clubteacher',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='core.schoolclub'),
        ),
        migrations.AlterField(
            model_name='studentclubmembership',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.schoolclub'),
        ),
        migrations.AlterField(
            model_name='talentsubmission',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='core.schoolclub'),
        ),
        migrations.DeleteModel(
            name='ClubTalent',
        ),
        migrations.AddConstraint(
            model_name='countryclub',
            constraint=models.UniqueConstraint(fields=('country', 'name'), name='unique_country_club_name'),
        ),
        migrations.AddConstraint(
            model_name='schoolclub',
            constraint=models.UniqueConstraint(fields=('school', 'country_club'), name='unique_school_club_selection'),
        ),
        migrations.DeleteModel(
            name='Club',
        ),
    ]
