# Generated by Django 5.2.17 on 2026-09-02 20:45

import django.db.models.deletion
from django.db import migrations, models


def migrate_talent_categories(apps, schema_editor):
    """Migrate existing category CharField values to new TalentCategory ForeignKey."""
    TalentCategory = apps.get_model('core', 'TalentCategory')
    Talent = apps.get_model('core', 'Talent')
    
    # Map of category values to display names
    category_names = {
        'music': 'Music',
        'sports': 'Sports',
        'technology': 'Technology',
        'arts': 'Arts',
        'academics': 'Academics',
        'other': 'Other',
    }
    
    # Get unique category values from existing Talent records
    existing_categories = Talent.objects.values_list('category', flat=True).distinct()
    
    # Create TalentCategory records and migrate Talent data
    for category_value in existing_categories:
        if category_value:
            display_name = category_names.get(category_value, category_value.title())
            category_obj, created = TalentCategory.objects.get_or_create(
                name=display_name,
                defaults={'description': f'Category for {display_name}'}
            )
            # Update talents with this category value
            Talent.objects.filter(category=category_value).update(category_id=category_obj.id)


def reverse_migrate(apps, schema_editor):
    """Reverse is not supported."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_club_school_remove_club_talents_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Talent Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='talent',
            name='category_id_new',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='talents', to='core.talentcategory'),
        ),
        migrations.RunPython(migrate_talent_categories, reverse_migrate),
        migrations.RemoveField(
            model_name='talent',
            name='category',
        ),
        migrations.RenameField(
            model_name='talent',
            old_name='category_id_new',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='talent',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='talents', to='core.talentcategory'),
        ),
        migrations.AlterModelOptions(
            name='talent',
            options={'ordering': ['category__name', 'name']},
        ),
    ]
