# Generated by Django 5.2.17 on 2026-09-08 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_talentcategory_alter_talent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='physical_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
